### ISSUE TITLE
Finalising V1

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/open-tourism-platform#117]
There a few things we need to sort out so the V1 of the API can be used effectively (mainly in the events app)

- [x] DB Field naming conventions #96 
- [x] append the api routes with /api/ ? #105 
- [x] date-related query params for getAll events #107 (PR #116)
- [x] finalise the fixed categories #82

Then there are a couple which we should sort out at some point soon but aren't necessarily urgent for the API to be used
 
- [ ] sorting of returned items from GET requests #81 (has been done for events, do we need to worry about other routes now?)
- [ ] don't return '__v' field from requests #97

@des-des Can you meet at 6pm your time?

**Comment by mattlub** [comment]
also finalising other routes, like using `/auth` or `/oauth`

**Comment by des-des** [comment]
@m4v15 Super sorry, I totes missed this, not sure how

**Comment by mattlub** [comment]
also finalising required fields etc.

**Comment by mattlub** [comment]
I would say "append the api routes with /api/ ? #105" needs to be decided, but the other 2 are enhancements and not urgent

**Comment by mattlub** [comment]
closed because v1 was finalised
