### ISSUE TITLE
Verification to OTP

### ISSUE THREAD

**Issue by Karyum** [foundersandcoders/open-tourism-platform#177]
This means having 2 kinds of data, ones that are **verified** ( verified as in an admin approved adding it to the API ) and **unverified**.
only verified data should be shown/rendered in the OTP child apps ( like Nazareth events ).

to implement a feature like this we might need these changes: 
- [x] change the API's database schema (places, events) to have an extra key of verified (which would be Boolean ) https://github.com/foundersandcoders/open-tourism-platform/issues/179
*Note: the data would be added to the database even if not yet verified.*
- [ ] send an email to the OTP admins so they could verify the data. #178 
- [x] A new route in the API which changes the `verified` key in the data to `true`. #181 
- [x] Changes to the way Nazareth events renders data https://github.com/foundersandcoders/nazareth-events/issues/182
- [ ] OTP data entry: 
  - [x]   add the status of the data (verified unverified). https://github.com/foundersandcoders/OTP-Data-Entry/issues/104
  - [ ]   add an ability for the admins to verify data from the app

have i missed anything @des-des ?

**Comment by des-des** [comment]
@Karyum You nailed it!
