### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/open-tourism-platform#27]
UPDATE - Making this the Epic for Auth 14/08/17
----
We have spent sprint 2 setting up the auth, but as we didn't know exactly what we were doing we haven't raised issues particularly well or documented our progress. I am now going to attempt to break up what we have done so far and what more we need to do. This epic issue can then be broken down.

## How Authorisation and Authentication will work on OTP

1. Anyone can register to be a user on OTP, will get a default `role` of `BASIC`
2. Routes will be secured by checking a users `role` and seeing if they are allowed on that route.
3. Further fine level permissioning (i.e. what fields different users can edit) will be also be done.
4. Apps will be able to make requests on behalf of a user once they have been authorised by that user. The app will have the same level of permissions as the user who authorised them.

### User Authentication / sessions

1. User logs in, has details added to cookie
2. Secure routes check cookie and scope of the route, let through or don't let through

More detail in #100 and have begun to be addressed in #95 

### OAuth
- Users [oath2-server](https://github.com/oauthjs/node-oauth2-server)
1. Superuser registers apps on the platform, giving them a client_id and a client_secret and a redirecitURI
2. App directs user to `oath/authorize` for user to authorise the app on their behalf (with the app's client id and redirect URI)
3. If the user authorises the app, it will make a `POST /oath/authorize` request. oath2-server will then use a (custom) authenticate handler to return the correct user, and then will redirect back to the redirect URI with an authorisation code(temp)
4. This redirect URI (within the app) will need to make `POST /oath/token` request, with the client id, client secret and the temp auth code, and will be sent back a permaneant token.
5. The app can then store this token somewhere and use it to make requests on the users behalf.
6. The secure routes will now check if there is a JWT in the cookie, on an auth token in a header, allowing them through as though they are the user (or have the users role) either way.

Initial steps addressed in #92.

### Permissioning

Yet to be started, but this is actually the point of all the auth. Can refer to the spec and lots of previous discussions about who can do what, will mostly be just checking the `role` or the `userid` (to see if they're the owner).

## To do:

- [x] Finish sessions #100
- [x] Write the custom Authentication handler for oauth2-server
- [x] add middleware that looks for oath token in header
- [x] Add views for UI #104 
  - [x] Set up handlebars and tachyons
  - [x] Add and serve views for login, register user, authorise app routes (`GET` requests)
- [x] Add the authentication middleware into the appropriate routes
  - [x] Specifically, `/oath/authorize` needs to be secure
  - [ ] decide on the other routes
- [ ] Permissioning

ORIGINAL ISSUE
---
WIP: task list to be finalised

- get auth data from JWT
    - decide what's in the JWT (userID, role?)
- create authentication function for each db collection (users, businesses, events, products, +others?) for each of:

  - GET
       - write test(1h)
        - write auth function(1h)
  - POST
       - write test(1h)
        - write auth function(1h)
  - UPDATE
       - write test(1h)
        - write auth function(1h)
  - DELETE
       -  write test(1h)
        -  write auth function(1h)

- repeat for other collections, either all separately or grouping them into common outcomes.

**Comment by mattlub** [comment]
I think this needs updating- @des-des could you post your ideas, including the simplest method?

**Comment by mattlub** [comment]
### basic JWT option

#### overview (wrt the platform):
- the api does not know/care where the request has come from
- JWTs are issued containing user's id and role from a `/login` route or similar
- JWTs are parsed on the server by middleware
- request is checked (method, and fields if PUT or POST) then either passed through or rejected

#### immediate tasks for this option:
- add /login route
- update `users` schema and routes- specifically password hashing 
- add JWT parsing middleware and logic

#### questions/potential problems (I haven't though them through much yet, want to discuss):
- how secure is this:
  - e.g. sending back a token to a specific app, won't the apps have to store these tokens?
- how does "logging in" with an app correspond with "logging in" with the platform?
- individual apps have to also issue their own tokens for logged in users
- **main question**: how does the flow look for apps?

comments? @m4v15 @mantagen @des-des @JWLD

**Comment by m4v15** [comment]
This option:

app (client) | platform
---|---
log in (directly on platform)|
 -|verify login, issue token (with timeout?)
store token (local storage?)|
make some request with JWT|
-| middleware (on all routes) checks token, adds relevant things to the request
-| middleware on each route then checks the request and passed or rejected
-| not 100% on the fine grain permissioning (fields etc)

So @des-des isn't entirely sure this is a good thing to do, it seems weird and we can't think of any other examples of using a third party direct log in - might be insecure like @mattlub suggests

Alternative, we build our own OAuth server:


app (client) |app (server)| platform
---|---|---
log in form posts to something like `OTP.com/login?app.id=1234`  the app id has been issued by us, along with a callback URL and a secret code that matches the ID|
-|-|verifies login and temp access token sent back to callback URL
-| requests permanent access token using the temp one and the secret code|-
-| -| issues permanent token after verifying secret code matches app.id
-| stores token (in cookie?) | -
-|make some request with JWT|
-|-| middleware (on all routes) checks token, adds relevant things to the request
-|-| middleware on each route then checks the request and passed or rejected

We can look into using this: https://www.npmjs.com/package/node-oauth2-server

Need to think about:
 - how we issue app ids and codes and set callback URLs
 - how long the tokens last for
 - this requires all the apps to have a backend

@des-des can maybe be more hands on, and look into using the above npm module

**Comment by m4v15** [comment]
https://tech.zilverline.com/2017/03/17/nodejs-oauth2-provider might help

**Comment by m4v15** [comment]
@des-des can we close this issue as permissioning now has it's own more detailed issue (#134) for sprint 4?

**Comment by des-des** [comment]
Cool. Closing with permission stuff moved to #134
