### ISSUE TITLE
Initial server setup

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/open-tourism-platform#32]
- [x] set up basic node server #34 
 - [x] set up local mongo and link to server #35
 - [x] deploy to heroku #36
